name: ipotec
description: "IpoTec"
publish_to: 'none'
version: 1.1.0+11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  get: ^4.6.6
  go_router: ^13.2.0
  get_storage: ^2.1.1

  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  lottie: ^3.1.2

  intl: ^0.19.0
  logger: ^2.4.0

  package_rename: ^1.5.3
  flutter_native_splash: ^2.4.1
  internet_connection_checker: ^1.0.0+1

  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.1.5
  flutter_html: ^3.0.0-beta.2

#  device_apps: ^2.2.0
  package_info_plus: ^4.0.0
  device_info_plus: ^10.1.2

  in_app_update: ^4.2.0


  #Firebase Dependency + notification
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.2.0
  firebase_analytics: ^10.3.0
  firebase_messaging: ^14.7.10
  firebase_performance: ^0.9.4+7
  flutter_local_notifications: ^18.0.1

  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5

  in_app_review: ^2.0.9
  share_plus: ^10.1.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bottom/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
    - assets/lottie/
    - assets/intro/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For



  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400

        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500

        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/icons/logo.png"
  android_12:
    image: "assets/icons/logo.png"