name: ipotec
description: "IpoTec"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  package_rename: ^1.5.3
  dio: ^5.4.1
  get: ^4.6.6
  go_router: ^13.2.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bottom/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For



  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
